# Site
title:          Aston's website
bio:            '随便看看，随便逛逛'
description:    "Simple Jekyll theme for your blog by Taylan Tatlı"
picture:        'assets/img/Logo.svg'
locale:         zh_CN
url:            https://www.hiahiahia.top

# Jekyll
permalink:      /:title/
markdown:       kramdown
highlighter:    rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed

# Social
twitter: AstonPython
facebook: 100069336799526
github: PyAston

# Paginate
# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [start.bat, README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]

# Personal Catalogy

# ham
collections:
  ham:
    output: true
    permalink: /ham/:path/

languages:
  - en
  - zh

